import { createAstronautPreview } from "../three/astronautPreview";

const NAV_ITEMS = [
  ["overview", "⌂", "Overview"], ["academics", "▤", "Academics"],
  ["students", "♟", "Students"], ["people", "◎", "People"],
  ["achievements", "★", "Achievements"], ["inventory", "▦", "Quests & Inventory"], ["avatar", "◉", "Avatar"],
  ["simulations", "◇", "Learning Labs"], ["chat", "◌", "Class Chat"]
];
const SAMPLE_GRADES = [["Life Science", "A−", 92, "Ecosystem interactions"], ["Earth Science", "B+", 88, "Rock cycle & minerals"], ["Scientific Practice", "A", 96, "Evidence and explanations"]];
const ACHIEVEMENTS = [["Science 101", "Unit medallion", "Earned", "unit-science"], ["Geology on Mars", "Unit medallion", "Earned", "unit-geology"], ["Field Researcher", "Complete your first investigation", "Earned", "field"], ["Evidence Builder", "Submit 5 evidence-based explanations", "3 / 5", "evidence"], ["Systems Thinker", "Balance an ecosystem simulation", "Locked", "systems"]];
const STUDY_UNITS = {
  "Science 101": ["Scientific Thinking", "Matter & Energy", "Living Systems"],
  "Geology on Mars": ["The Red Planet", "Rocks & Minerals", "Planetary Change"]
};
const SPHERES = [
  ["Geosphere", "Rock and plant samples are more likely", "◆", "rock + plant"],
  ["Atmosphere", "Specimen and water samples are more likely", "◌", "specimen + water"],
  ["Hydrosphere", "Water and plant samples are more likely", "≈", "water + plant"],
  ["Biosphere", "Plant and specimen samples are more likely", "❋", "plant + specimen"]
];
const STUDY_QUESTIONS = [
  { prompt: "Which Earth system includes rocks, minerals, and landforms?", answers: ["Geosphere", "Atmosphere", "Hydrosphere", "Biosphere"], correct: 0 },
  { prompt: "Which observation is strongest evidence in a scientific explanation?", answers: ["A repeated measurement", "A personal preference", "An unsupported guess", "A decorative diagram"], correct: 0 },
  { prompt: "Water moving from a lake into the air is called…", answers: ["Evaporation", "Erosion", "Deposition", "Freezing"], correct: 0 },
  { prompt: "A population is best described as…", answers: ["Members of one species in an area", "Every nonliving factor", "All planets in a system", "One individual organism"], correct: 0 }
];
const MISSION_UNITS = [
  { id: "science-101", title: "Science 101", destination: "Moon", chapters: 3, x: 14, y: 64 },
  { id: "geology-mars", title: "Geology of Mars", destination: "Mars", chapters: 3, x: 27, y: 48 },
  { id: "plate-motion", title: "Plate Motion", destination: "Io", chapters: 4, x: 40, y: 61 },
  { id: "rock-transformation", title: "Rock Transformation", destination: "Europa", chapters: 4, x: 51, y: 40 },
  { id: "phase-change", title: "Phase Change", destination: "Titan", chapters: 4, x: 64, y: 62 },
  { id: "chemical-reaction", title: "Chemical Reaction", destination: "Neptune", chapters: 4, x: 75, y: 39 },
  { id: "population-resources", title: "Population & Resources", destination: "Eridani Frontier", chapters: 3, x: 86, y: 59 },
  { id: "ecosystem-energy", title: "Matter & Energy in Ecosystems", destination: "Epsilon Eridani", chapters: 3, x: 95, y: 31 }
];
const MISSION_STOPS = [{ kind: "start", title: "Earth · Departure", x: 3, y: 71 }];
MISSION_UNITS.forEach((unit, unitIndex) => {
  const previous = MISSION_STOPS[MISSION_STOPS.length - 1];
  for (let chapter = 1; chapter <= unit.chapters; chapter += 1) {
    const ratio = chapter / (unit.chapters + 1);
    MISSION_STOPS.push({ kind: "chapter", title: `${unit.title} · Chapter ${chapter}`, unitIndex, chapter, x: previous.x + (unit.x - previous.x) * ratio, y: previous.y + (unit.y - previous.y) * ratio });
  }
  MISSION_STOPS.push({ kind: "unit", title: unit.title, destination: unit.destination, unitIndex, x: unit.x, y: unit.y });
});

function el(tag, className = "", text = "") { const node = document.createElement(tag); if (className) node.className = className; if (text) node.textContent = text; return node; }
function icon(name) { return `<span class="dashboard-icon" aria-hidden="true">${name}</span>`; }

export function createStudentDashboard({ root, isAdmin = false, classServers = [], missionPosition = 0, classroomStatus = {}, getStudent = () => ({}), getProgression = () => ({}), getInventory = () => ({}), getQuests = () => ({ quests: [] }), getItemDefinition = () => null, onEnterSimulation = () => {}, onOpenSettings = () => {}, onSendChat = () => false, onRequestQuest = () => false, onAnswerStudyQuestion = () => false, onSwitchClass = () => {}, onSetMissionPosition = () => {}, onConnectClassroom = async () => {}, onSyncClassroom = async () => ({}), onLoadClassRoster = async () => ({ students: [] }), onAddClassStudent = async () => ({}), onRemoveClassStudent = async () => ({}), onLoadStudentStats = async () => ({}), onLoadAccounts = async () => ({ accounts: [] }), onUpdateAccount = async () => ({}) } = {}) {
  if (!root) return null;
  root.querySelector("#student-dashboard")?.remove();
  const shell = el("main", "student-dashboard"); shell.id = "student-dashboard"; shell.setAttribute("aria-label", "Student learning dashboard");
  const sidebar = el("aside", "dashboard-sidebar");
  const brand = el("div", "dashboard-brand"); brand.innerHTML = `<div class="brand-mark">E³</div><div><strong>Epsilon Academy</strong><small>Learning Command</small></div>`;
  const nav = el("nav", "dashboard-nav"); const navButtons = {};
  NAV_ITEMS.forEach(([key, glyph, label], index) => { if ((key === "students" || key === "people") && !isAdmin) return; const button = el("button", `dashboard-nav-item${index === 0 ? " active" : ""}`); button.type = "button"; button.dataset.view = key; button.innerHTML = `${icon(glyph)}<span>${label}</span>`; nav.appendChild(button); navButtons[key] = button; });
  const sidebarFooter = el("div", "dashboard-sidebar-footer"); sidebarFooter.innerHTML = `<span class="status-dot"></span><div><strong>Class connected</strong><small>Teacher controls active</small></div>`; sidebar.append(brand, nav, sidebarFooter);
  const content = el("section", "dashboard-content"); const topbar = el("header", "dashboard-topbar"); const titleGroup = el("div", "dashboard-title-group"); titleGroup.innerHTML = `<span class="eyebrow">Student workspace</span><h1>Mission Overview</h1>`;
  const topActions = el("div", "dashboard-top-actions"); const classPill = el("div", "class-pill", "Period —"); const settings = el("button", "icon-button", "⚙"); settings.type = "button"; settings.title = "Settings"; settings.addEventListener("click", onOpenSettings);
  if (isAdmin) { const serverSelect = el("select", "teacher-server-select"); serverSelect.setAttribute("aria-label", "Active class server"); serverSelect.appendChild(new Option(classServers.length ? "Select class server…" : "No class servers available", "")); classServers.forEach(({ code, name }) => serverSelect.appendChild(new Option(name, code))); serverSelect.value = getStudent().classCode || ""; serverSelect.addEventListener("change", () => { if (serverSelect.value) onSwitchClass(serverSelect.value); }); topActions.appendChild(serverSelect); }
  const userChip = el("div", "user-chip"); userChip.innerHTML = `<span class="user-initial">S</span><div><strong>Student</strong><small class="rank-line">Recruit</small><small class="chapter-line">Current chapter: —</small></div>`; topActions.append(classPill, settings, userChip); topbar.append(titleGroup, topActions);
  const viewport = el("div", "dashboard-viewport"); content.append(topbar, viewport); shell.append(sidebar, content); root.appendChild(shell);
  let activeView = "overview"; let avatarPreview = null; let portalEnabled = true; let chatMessages = []; let achievementQueue = []; let activeAchievement = null; let studyContext = null; let studyQuestionIndex = 0; let studyProgress = 0; let currentMissionPosition = Math.max(0, Math.min(MISSION_STOPS.length - 1, Number(missionPosition) || 0));
  const achievementOverlay = el("div", "achievement-reveal");
  achievementOverlay.hidden = true;
  achievementOverlay.innerHTML = `<div class="confetti-field" aria-hidden="true"></div><div class="reveal-medallion"><span class="medal-glyph">✦</span><small>Achievement unlocked</small><strong>Achievement</strong><em>Continue</em></div><p>Click any button or press any key to continue</p>`;
  for (let i = 0; i < 42; i += 1) {
    const angle = Math.random() * Math.PI * 2; const radius = 150 + Math.random() * 290; const bit = el("i"); bit.style.setProperty("--burst-x", `${Math.cos(angle) * radius}px`); bit.style.setProperty("--burst-y", `${Math.sin(angle) * radius * .58}px`); bit.style.setProperty("--fall-x", `${Math.cos(angle) * (radius + 110)}px`); bit.style.setProperty("--fall-y", `${180 + Math.random() * 280}px`); bit.style.setProperty("--r", `${Math.random() * 240}deg`); bit.style.setProperty("--d", `${Math.random() * .18}s`); achievementOverlay.querySelector(".confetti-field").appendChild(bit);
  }
  shell.appendChild(achievementOverlay);
  function showNextAchievement() {
    activeAchievement = achievementQueue.shift() || null;
    if (!activeAchievement) { achievementOverlay.hidden = true; return; }
    achievementOverlay.querySelector(".medal-glyph").textContent = activeAchievement.glyph || "✦";
    achievementOverlay.querySelector("strong").textContent = activeAchievement.title || "New Achievement";
    achievementOverlay.querySelector("em").textContent = activeAchievement.detail || "Added to your record";
    achievementOverlay.hidden = false;
    achievementOverlay.querySelector(".reveal-medallion").classList.toggle("silver", activeAchievement.metal === "silver");
    achievementOverlay.classList.remove("bursting");
    void achievementOverlay.offsetWidth;
    achievementOverlay.classList.add("bursting");
  }
  function advanceAchievement(event) {
    if (achievementOverlay.hidden) return;
    if (event?.type === "keydown" || event?.type === "click") { event.preventDefault?.(); showNextAchievement(); }
  }
  achievementOverlay.addEventListener("click", advanceAchievement);
  window.addEventListener("keydown", advanceAchievement);
  const studentName = () => getStudent().name || "Student Explorer";
  const progressData = () => { const rank = getProgression()?.profileRank || {}; const xp = Number(rank.pointsIntoLevel ?? rank.xp ?? 0); const needed = Math.max(1, Number(rank.pointsForNextLevel) || 100); return { rank, xp, needed, percent: Math.min(100, Math.round((xp / needed) * 100)) }; };
  function card(title, body, className = "") { const section = el("section", `dashboard-card ${className}`.trim()); section.innerHTML = `<div class="card-heading"><h2>${title}</h2></div>`; section.appendChild(body); return section; }

  function renderOverview() {
    const { rank, xp, needed, percent } = progressData(); const wrap = el("div", "overview-layout"); const welcome = el("section", "welcome-card");
    welcome.innerHTML = `<div><span class="eyebrow">Welcome back</span><h2>${studentName()}</h2><p>Your learning record is ready. Continue an assignment or review your progress.</p><div class="xp-progress"><div><span>Experience progress</span><strong>${xp} / ${needed} XP</strong></div><div class="progress-track"><i style="width:${percent}%"></i></div></div></div><div class="level-orbit"><span>LEVEL</span><strong>${rank.level || 1}</strong><small>${rank.label || "Recruit"}</small></div>`;
    const stats = el("div", "stat-grid"); [["Current average", "92%", "↑ 3% this term"], ["Achievements", "8", "2 nearly complete"], ["Class ranking", "#7", "of 28 students"], ["Learning streak", "6 days", "Personal best: 11"]].forEach(([label, value, note]) => { const stat = el("article", "stat-card"); stat.innerHTML = `<span>${label}</span><strong>${value}</strong><small>${note}</small>`; stats.appendChild(stat); });
    const assignments = el("div", "assignment-list"); [["Ecosystem Carrying Capacity", "Life Science", "Due Friday", "Continue"], ["Mineral Evidence Log", "Earth Science", "Submitted", "Review"], ["Population Graph Reflection", "Scientific Practice", "Due Sep 18", "Begin"]].forEach(([name, subject, due, action], index) => { const row = el("div", "assignment-row"); row.innerHTML = `<span class="assignment-symbol">${["∿", "◆", "⌁"][index]}</span><div><strong>${name}</strong><small>${subject} · ${due}</small></div><button type="button">${action}</button>`; assignments.appendChild(row); });
    const activity = el("div", "activity-list"); activity.innerHTML = `<div><span class="activity-dot gold"></span><p><strong>Achievement unlocked</strong><small>Field Researcher · Yesterday</small></p></div><div><span class="activity-dot blue"></span><p><strong>12 XP earned</strong><small>Mineral Evidence Log · Sep 11</small></p></div><div><span class="activity-dot green"></span><p><strong>Grade updated to 92%</strong><small>Life Science · Sep 10</small></p></div>`;
    wrap.append(welcome, stats, card("Current learning", assignments), card("Recent activity", activity)); return wrap;
  }
  function renderAcademics() { const wrap = el("div", "page-stack"); const student = getStudent(); const classroomPercent = Number(student.googleClassroomPercent ?? 92); const summary = el("div", "section-intro"); summary.innerHTML = `<div><span class="eyebrow">Academic record</span><h2>Grades & feedback</h2><p>Progress here reflects learning evidence, not time spent in a game.</p></div><span class="term-chip">Google Classroom · ${classroomPercent}%</span>`; const classroom = el("div", "classroom-summary"); classroom.innerHTML = `<div class="classroom-mark">G</div><div><span>Google Classroom percentage</span><strong>${classroomPercent}%</strong><small>${student.className || "Current class"} · last synchronized grade</small></div><div class="classroom-progress"><i style="width:${Math.max(0, Math.min(100, classroomPercent))}%"></i></div>`; const table = el("div", "grade-table"); table.innerHTML = `<div class="grade-row grade-header"><span>Course</span><span>Grade</span><span>Progress</span><span>Current focus</span></div>`; SAMPLE_GRADES.forEach(([course, grade, score, focus]) => { const row = el("div", "grade-row"); row.innerHTML = `<strong>${course}</strong><b>${grade}</b><span><i><em style="width:${score}%"></em></i>${score}%</span><small>${focus}</small>`; table.appendChild(row); }); wrap.append(summary, classroom, card("Course progress", table)); if (isAdmin) { const controls = el("section", "dashboard-card classroom-controls"); controls.innerHTML = `<div><span class="eyebrow">Teacher integration</span><h2>Google Classroom</h2><p class="classroom-connection-status">${classroomStatus.connected ? `Connected as ${classroomStatus.email || "teacher"}` : classroomStatus.configured ? "Ready to connect" : "OAuth variables are not configured on the server"}</p></div><button type="button" data-classroom="connect">${classroomStatus.connected ? "Reconnect" : "Connect Google Classroom"}</button><button type="button" data-classroom="sync" ${classroomStatus.connected ? "" : "disabled"}>Synchronize classes & rosters</button>`; controls.addEventListener("click", async (event) => { const button = event.target.closest("button[data-classroom]"); if (!button) return; const status = controls.querySelector(".classroom-connection-status"); button.disabled = true; try { if (button.dataset.classroom === "connect") { status.textContent = "Opening Google authorization…"; await onConnectClassroom(); return; } status.textContent = "Synchronizing Classroom…"; const result = await onSyncClassroom(); status.textContent = `Imported ${result.courses || 0} classes and ${result.rosterEntries || 0} roster entries; ${result.matchedStudents || 0} existing E3 accounts matched.`; } catch (error) { status.textContent = error?.message || "Google Classroom action failed."; } finally { button.disabled = false; } }); wrap.appendChild(controls); } return wrap; }
  function renderMissionMap() {
    const map = el("section", "mission-journey");
    const routePoints = MISSION_STOPS.map((stop) => `${stop.x * 10},${stop.y * 4}`).join(" ");
    map.innerHTML = `<div class="mission-map-heading"><div><span class="eyebrow">Expedition progress</span><h2>Voyage to Epsilon Eridani</h2><p>Gold destinations mark units. Silver signals on the route mark ${MISSION_UNITS.reduce((total, unit) => total + unit.chapters, 0)} chapters.</p></div></div><div class="mission-map-stage"><img class="mission-space-art" src="assets/ui/mission/e3-space-route.png" alt="Planetary voyage from Earth toward Epsilon Eridani"><svg class="mission-route-line" viewBox="0 0 1000 400" preserveAspectRatio="none" aria-hidden="true"><polyline fill="none" stroke="rgba(127,229,234,.62)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="9 9" points="${routePoints}"/></svg><div class="mission-start">Earth · Departure</div><div class="mission-chapter-dots"></div><div class="mission-destinations"></div><img class="mission-map-ship" src="assets/ui/mission/e3-expedition-ship.png" alt="E3 expedition ship"></div>`;
    const destinationLayer = map.querySelector(".mission-destinations"); const dotsLayer = map.querySelector(".mission-chapter-dots");
    MISSION_UNITS.forEach((unit, unitIndex) => { const stopIndex = MISSION_STOPS.findIndex((stop) => stop.kind === "unit" && stop.unitIndex === unitIndex); const button = el("button", `mission-destination${stopIndex <= currentMissionPosition ? " reached" : ""}${stopIndex === currentMissionPosition ? " current" : ""}`); button.type = "button"; button.style.left = `${unit.x}%`; button.style.top = `${unit.y}%`; button.innerHTML = `<i></i><strong>${unit.destination}</strong><small>${unit.title}</small>`; button.addEventListener("click", () => { achievementQueue.push({ title: unit.title, detail: `${unit.destination} · ${unit.chapters} chapters`, glyph: unitIndex === MISSION_UNITS.length - 1 ? "✦" : "◉", metal: "gold" }); showNextAchievement(); }); destinationLayer.appendChild(button); });
    MISSION_STOPS.forEach((stop, stopIndex) => { if (stop.kind !== "chapter") return; const dot = el("button", `mission-chapter-dot${stopIndex < currentMissionPosition ? " complete" : ""}${stopIndex === currentMissionPosition ? " current" : ""}`); dot.type = "button"; dot.style.left = `${stop.x}%`; dot.style.top = `${stop.y}%`; dot.title = stop.title; dot.setAttribute("aria-label", `View achievement for ${stop.title}`); dot.addEventListener("click", () => { achievementQueue.push({ title: `Chapter ${stop.chapter}`, detail: MISSION_UNITS[stop.unitIndex].title, glyph: "✦", metal: "silver" }); showNextAchievement(); }); dotsLayer.appendChild(dot); });
    const current = MISSION_STOPS[currentMissionPosition]; const ship = map.querySelector(".mission-map-ship"); ship.style.left = `${current.x}%`; ship.style.top = `${current.y}%`;
    if (isAdmin) { const control = el("div", "mission-position-control"); control.innerHTML = `<div class="mission-position-actions"><button type="button" data-step="-1" ${currentMissionPosition === 0 ? "disabled" : ""}>Undo advance</button><button type="button" data-step="1" ${currentMissionPosition === MISSION_STOPS.length - 1 ? "disabled" : ""}>Advance one stop</button></div><span class="mission-position-status"><small>Ship position</small><strong>${current.title}</strong></span>`; control.addEventListener("click", (event) => { const button = event.target.closest("button[data-step]"); if (!button) return; currentMissionPosition = Math.max(0, Math.min(MISSION_STOPS.length - 1, currentMissionPosition + Number(button.dataset.step))); onSetMissionPosition(currentMissionPosition); render("achievements"); }); map.querySelector(".mission-map-heading").appendChild(control); }
    return map;
  }
  function renderAchievements() { const wrap = el("div", "page-stack"); const heading = el("div", "section-intro"); heading.innerHTML = `<div><span class="eyebrow">Milestones</span><h2>Academic achievements</h2><p>Badges recognize demonstrated skills and completed learning goals.</p></div>`; const grid = el("div", "achievement-grid"); ACHIEVEMENTS.forEach(([name, description, state, kind], index) => { const item = el("article", `achievement-card ${state === "Earned" ? "earned" : ""} ${kind}`); item.innerHTML = `<div class="achievement-medal">${["☀", "◆", "✦", "⬡", "◎"][index]}</div><div><span>${state}</span><h3>${name}</h3><p>${description}</p></div>`; grid.appendChild(item); }); wrap.append(heading, renderMissionMap(), grid); if (isAdmin) { const controls = el("section", "dashboard-card achievement-controls"); controls.innerHTML = `<div><span class="eyebrow">Teacher controls</span><h2>Award achievements</h2><p>Award a milestone to one student or the whole class.</p></div><select aria-label="Achievement recipient"><option>Whole class</option><option>Current student preview</option></select><button type="button" data-award="Science 101">Award New Unit: Science 101</button><button type="button" data-award="Geology on Mars">Award New Unit: Geology on Mars</button><button type="button" data-award="New Chapter">Award New Chapter</button>`; controls.addEventListener("click", (event) => { const button = event.target.closest("button[data-award]"); if (!button) return; const title = button.dataset.award; achievementQueue.push({ title, detail: title === "New Chapter" ? `Chapter: ${getStudent().currentChapter || "New chapter"}` : `Unit: ${title}`, glyph: title.includes("Geology") ? "◆" : title === "New Chapter" ? "◉" : "☀" }); showNextAchievement(); }); wrap.appendChild(controls); } return wrap; }
  function renderStudents() {
    const wrap = el("div", "page-stack teacher-roster-page");
    const activeClass = classServers.find((entry) => entry.code === getStudent().classCode) || classServers[0];
    wrap.innerHTML = `<div class="section-intro"><div><span class="eyebrow">Teacher controls</span><h2>Class roster</h2><p>Classroom students appear automatically after synchronization. Their verified Google sign-in email links them to E3.</p></div></div>`;
    if (!activeClass?.id) { wrap.appendChild(el("section", "dashboard-card roster-empty", "Select a class server above to view its students.")); return wrap; }
    const form = el("form", "dashboard-card roster-add-form");
    form.innerHTML = `<div><span class="eyebrow">Authorize an email</span><h3>${activeClass.name}</h3></div><input name="displayName" aria-label="Student name" placeholder="Student name (optional)"><input name="email" type="email" required aria-label="Student email" placeholder="student@school.org"><button type="submit">Allow Google sign-in</button><small class="roster-form-status"></small>`;
    const layout = el("div", "roster-layout"); const list = el("section", "dashboard-card roster-list"); const detail = el("aside", "dashboard-card roster-detail");
    list.innerHTML = `<div class="roster-loading">Loading students…</div>`; detail.innerHTML = `<span class="eyebrow">Student overview</span><h3>Select a student</h3><p>Click a linked student to view their E3 account status and inventory summary.</p>`; layout.append(list, detail); wrap.append(form, layout);
    const load = async () => {
      try {
        const result = await onLoadClassRoster(activeClass.id); const students = result.students || [];
        list.innerHTML = `<div class="card-heading"><div><span class="eyebrow">${students.length} students</span><h2>${result.class?.name || activeClass.name}</h2></div></div><div class="roster-rows"></div>`;
        const rows = list.querySelector(".roster-rows");
        if (!students.length) rows.appendChild(el("p", "roster-empty", "No students yet. Synchronize Google Classroom or add one by email."));
        students.forEach((student) => {
          const row = el("div", `roster-row${student.inClass ? " linked" : ""}`); row.innerHTML = `<button type="button" class="roster-student"><span class="roster-avatar">${(student.displayName || "S").charAt(0).toUpperCase()}</span><span><strong>${student.displayName}</strong><small>${student.email || "Email hidden by Google"}</small></span></button><span class="roster-source">${student.inClass ? "E3 linked" : "Ready for Google"}</span>${student.inClass ? `<button type="button" class="roster-remove">Remove</button>` : ""}`;
          row.querySelector(".roster-student").disabled = !student.inClass;
          row.querySelector(".roster-student").addEventListener("click", async () => { detail.innerHTML = `<p>Loading overview…</p>`; try { const stats = (await onLoadStudentStats(activeClass.id, student.userId)).student; detail.innerHTML = `<span class="eyebrow">Student overview</span><h3>${stats.displayName}</h3><p>${stats.email || "No email available"}</p><div class="roster-stat-grid"><div><strong>${stats.online ? "Online" : "Offline"}</strong><small>Connection</small></div><div><strong>${stats.inventoryItems}</strong><small>Inventory items</small></div><div><strong>${stats.inventoryTypes}</strong><small>Item types</small></div></div><p class="roster-note">Grades, XP, achievements, level, and ranking will appear here as those overview values are moved into persistent student records.</p>`; } catch (error) { detail.innerHTML = `<p>${error?.message || "Could not load student overview."}</p>`; } });
          row.querySelector(".roster-remove")?.addEventListener("click", async (event) => { const button = event.currentTarget; button.disabled = true; try { await onRemoveClassStudent(activeClass.id, student.userId); await load(); } catch (error) { button.disabled = false; detail.innerHTML = `<p class="roster-error">${error?.message || "Could not remove the student."}</p>`; } });
          rows.appendChild(row);
        });
      } catch (error) { list.innerHTML = `<p class="roster-error">${error?.message || "Could not load the class roster."}</p>`; }
    };
    form.addEventListener("submit", async (event) => { event.preventDefault(); const status = form.querySelector(".roster-form-status"); const button = form.querySelector("button"); button.disabled = true; status.textContent = "Authorizing email…"; try { const result = await onAddClassStudent(activeClass.id, { email: form.elements.email.value, displayName: form.elements.displayName.value }); status.textContent = result.pendingGoogleSignIn ? "Email authorized. The student can now use Sign in with Google—no invitation email was sent." : "Existing E3 account linked to this class."; form.reset(); await load(); } catch (error) { status.textContent = error?.message || "Could not authorize student."; } finally { button.disabled = false; } });
    load(); return wrap;
  }
  function renderPeople() {
    const wrap = el("div", "page-stack people-admin-page");
    wrap.innerHTML = `<div class="section-intro"><div><span class="eyebrow">Account administration</span><h2>People & access</h2><p>New Google logins appear here. Assign students to a class or promote an account to teacher access.</p></div></div>`;
    const panel = el("section", "dashboard-card people-list"); panel.innerHTML = `<p>Loading accounts…</p>`; wrap.appendChild(panel);
    const load = async () => { try { const result = await onLoadAccounts(); const accounts = result.accounts || []; panel.innerHTML = `<div class="inventory-toolbar"><div><span class="eyebrow">${accounts.length} accounts</span><h2>Recent logins</h2></div><span>Newest first</span></div><div class="people-rows"></div>`; const rows = panel.querySelector(".people-rows"); accounts.forEach((account) => { const row = el("article", "people-row"); const classOptions = [`<option value="">Unassigned</option>`, ...classServers.map((entry) => `<option value="${entry.id}" ${entry.id === account.classId ? "selected" : ""}>${entry.name}</option>`)].join(""); row.innerHTML = `<div class="people-identity"><span class="roster-avatar">${(account.displayName || "U").charAt(0).toUpperCase()}</span><span><strong>${account.displayName}</strong><small>${account.email}</small><em>${account.lastSignInAt ? `Last login ${new Date(account.lastSignInAt).toLocaleDateString()}` : "Account created; no completed login yet"}</em></span></div><label>Role<select class="people-role"><option value="student" ${account.role === "student" ? "selected" : ""}>Student</option><option value="teacher" ${account.role === "teacher" ? "selected" : ""}>Teacher</option></select></label><label>Class<select class="people-class" ${account.role === "teacher" ? "disabled" : ""}>${classOptions}</select></label><button type="button">Save access</button><small class="people-status"></small>`; const role = row.querySelector(".people-role"); const classSelect = row.querySelector(".people-class"); role.addEventListener("change", () => { classSelect.disabled = role.value === "teacher"; }); row.querySelector("button").addEventListener("click", async (event) => { const button = event.currentTarget; const status = row.querySelector(".people-status"); button.disabled = true; status.textContent = "Saving…"; try { const updated = await onUpdateAccount(account.userId, { role: role.value, classId: classSelect.value }); status.textContent = updated.requiresRelogin ? "Saved. This person should log out and back in." : "Saved."; } catch (error) { status.textContent = error?.message || "Could not update access."; } finally { button.disabled = false; } }); rows.appendChild(row); }); } catch (error) { panel.innerHTML = `<p class="roster-error">${error?.message || "Could not load accounts."}</p>`; } };
    load(); return wrap;
  }
  function renderAvatar() { const wrap = el("div", "avatar-layout avatar-only-layout"); const preview = el("div", "dashboard-avatar-preview"); const stage = el("div", "dashboard-avatar-stage"); preview.appendChild(stage); const caption = el("div", "avatar-caption"); caption.innerHTML = `<span>3D avatar</span><h2>${studentName()}</h2><p>Outfit choices and wearable customization will appear here.</p>`; preview.appendChild(caption); const coming = el("section", "dashboard-card outfit-preview"); coming.innerHTML = `<span class="eyebrow">Outfit bay</span><h2>Outfits coming next</h2><p>Your avatar is now separate from collected samples and quests. Future suits, helmets, and accessories will be managed on this page.</p>`; wrap.append(preview, coming); requestAnimationFrame(() => { avatarPreview = createAstronautPreview(stage); }); return wrap; }
  function renderInventoryAndQuests() { const wrap = el("div", "page-stack"); const counts = getInventory() || {}; const keys = Object.keys(counts).filter((key) => Number(counts[key]) > 0).slice(0, 24); const inventory = el("section", "dashboard-card inventory-browser"); inventory.innerHTML = `<div class="inventory-toolbar"><div><span class="eyebrow">Collection</span><h2>Scientific inventory</h2></div><span>${keys.length} item types</span></div>`; const grid = el("div", "dashboard-inventory-grid"); (keys.length ? keys : ["rock_sample", "plant_sample", "water_sample", "herbivore_specimen"]).forEach((key, index) => { const def = getItemDefinition(key) || {}; const item = el("div", "inventory-tile"); item.innerHTML = `${def.imageSrc ? `<img src="${def.imageSrc}" alt="">` : `<span>${["◆", "❋", "≈", "◌"][index % 4]}</span>`}<strong>${def.label || key.replaceAll("_", " ")}</strong><small>× ${counts[key] || 0}</small>`; grid.appendChild(item); }); inventory.appendChild(grid); const quests = el("section", "dashboard-card dashboard-quest-list"); const snapshot = getQuests() || {}; const active = snapshot.quests || []; quests.innerHTML = `<div class="inventory-toolbar"><div><span class="eyebrow">Sample missions</span><h2>Active quests</h2></div><span>${active.length}/${snapshot.maxQuests || 5}</span></div><div class="quest-list-body"></div>`; const body = quests.querySelector(".quest-list-body"); if (!active.length) body.innerHTML = `<p>No active quests. Receive one from the Learning Labs.</p>`; active.forEach((quest) => { const row = el("article", "dashboard-quest-row"); row.innerHTML = `<strong>${quest.resourceLabel || "Sample collection"}</strong><span>${quest.progress || 0}/${quest.requiredCount || 1} · ${quest.minimumQuality || "common"} or better</span><small>${quest.ready ? "Ready to complete in the Original E3 World" : "Collect matching samples to complete this quest"}</small>`; body.appendChild(row); }); wrap.append(inventory, quests); return wrap; }
  function renderSimulations() {
    const wrap = el("div", "page-stack");
    const heading = el("div", "section-intro");
    heading.innerHTML = `<div><span class="eyebrow">Teacher-directed activities</span><h2>Learning Labs</h2><p>Choose a simulation or open the question-based study archive.</p></div><span class="portal-status ${portalEnabled ? "open" : ""}">${portalEnabled ? "Labs online" : "Labs paused"}</span>`;
    const destinations = el("div", "lab-destination-grid");
    destinations.innerHTML = `<article class="lab-destination original-world"><span>EXPEDITION SIMULATION</span><h3>Original E3 World</h3><p>Enter the original multiplayer field simulation with exploration, resources, quests, and portals.</p><button type="button" ${portalEnabled ? "" : "disabled"}>Enter simulation</button></article><article class="lab-destination study-archive"><span>QUESTION EXPEDITION</span><h3>Orbital Study Archive</h3><p>Answer chapter questions and earn weighted samples for every correct response.</p><button type="button" ${portalEnabled ? "" : "disabled"}>Plan an expedition</button></article>`;
    destinations.querySelector(".original-world button").addEventListener("click", () => onEnterSimulation("original"));
    const planner = el("section", "dashboard-card study-planner");
    planner.innerHTML = `<div class="study-step"><span>01</span><label>Unit<select id="study-unit">${Object.keys(STUDY_UNITS).map((unit) => `<option>${unit}</option>`).join("")}</select></label></div><div class="study-step"><span>02</span><label>Chapter<select id="study-chapter"></select></label></div><div class="study-step sphere-step"><span>03</span><div><strong>Choose a sphere</strong><small>Sphere choice changes sample-type probability. Original rarity odds remain unchanged.</small></div></div><div class="sphere-grid"></div><div class="study-actions"><div><strong>Field quests available</strong><small>Original quest odds, delay, and five-quest maximum apply</small></div><button type="button" class="quest-request">Receive a new quest</button></div>`;
    planner.hidden = true;
    destinations.querySelector(".study-archive button").addEventListener("click", () => { planner.hidden = false; planner.scrollIntoView({ behavior: "smooth", block: "start" }); });
    const unitSelect = planner.querySelector("#study-unit"); const chapterSelect = planner.querySelector("#study-chapter");
    const fillChapters = () => { chapterSelect.innerHTML = STUDY_UNITS[unitSelect.value].map((chapter) => `<option>${chapter}</option>`).join(""); }; fillChapters(); unitSelect.addEventListener("change", fillChapters);
    SPHERES.forEach(([name, description, glyph, bonus]) => { const sphere = el("button", `sphere-option ${name.toLowerCase()}`); sphere.type = "button"; sphere.disabled = !portalEnabled; sphere.innerHTML = `<span>${glyph}</span><strong>${name}</strong><small>${description}</small><em>Boost: ${bonus}</em>`; sphere.addEventListener("click", () => { studyContext = { unit: unitSelect.value, chapter: chapterSelect.value, sphere: name }; studyQuestionIndex = 0; studyProgress = 0; render("study"); }); planner.querySelector(".sphere-grid").appendChild(sphere); });
    planner.querySelector(".quest-request").addEventListener("click", () => onRequestQuest()); wrap.append(heading, destinations, planner);
    if (isAdmin) { const controls = el("section", "admin-lab-controls dashboard-card"); controls.innerHTML = `<div><span class="eyebrow">Teacher controls</span><h2>Learning Lab access</h2><p>Control all destinations for this class or configure individual access.</p></div><label><span>Enable for whole class</span><input type="checkbox" ${portalEnabled ? "checked" : ""}></label><button type="button">Individual students</button>`; controls.querySelector("input").addEventListener("change", (event) => { portalEnabled = event.target.checked; render("simulations"); }); wrap.appendChild(controls); }
    return wrap;
  }
  function renderStudySession() {
    const wrap = el("div", "study-session"); const question = STUDY_QUESTIONS[studyQuestionIndex % STUDY_QUESTIONS.length];
    wrap.innerHTML = `<div class="study-session-header"><button type="button">← Learning Labs</button><div><span>${studyContext?.unit} · ${studyContext?.chapter}</span><h2>${studyContext?.sphere} Expedition</h2></div><em>Question ${studyQuestionIndex + 1}</em></div><div class="study-mastery" role="progressbar" aria-label="Study progress" aria-valuemin="0" aria-valuemax="10" aria-valuenow="${studyProgress}"><i style="width:${studyProgress * 10}%"></i></div><section class="study-question-card"><span>ARCHIVE PROMPT</span><h3></h3><div class="study-answer-grid"></div><p class="study-feedback">Fill the bar with correct answers. An incorrect answer removes three steps.</p></section>`;
    wrap.querySelector("h3").textContent = question.prompt; wrap.querySelector(".study-session-header button").addEventListener("click", () => render("simulations"));
    question.answers.forEach((answer, index) => { const button = el("button", "study-answer", answer); button.type = "button"; button.addEventListener("click", () => { const feedback = wrap.querySelector(".study-feedback"); wrap.querySelectorAll(".study-answer").forEach((entry) => { entry.disabled = true; }); if (index !== question.correct) { button.classList.add("wrong"); studyProgress = Math.max(0, studyProgress - 3); feedback.textContent = "Incorrect. The mastery signal dropped—next question incoming."; } else { button.classList.add("correct"); studyProgress = Math.min(10, studyProgress + 1); feedback.textContent = studyProgress >= 10 ? "Mastery achieved! Your sphere sample is being transmitted." : "Correct. The mastery signal increased."; } if (studyProgress >= 10) { onAnswerStudyQuestion(studyContext); window.setTimeout(() => { studyProgress = 0; studyQuestionIndex += 1; render("inventory"); }, 1600); return; } window.setTimeout(() => { studyQuestionIndex += 1; render("study"); }, 900); }); wrap.querySelector(".study-answer-grid").appendChild(button); });
    return wrap;
  }
  function renderChat() { const wrap = el("div", "chat-page"); const transcript = el("section", "dashboard-card dashboard-chat"); transcript.innerHTML = `<div class="card-heading"><div><span class="eyebrow">Same shared room</span><h2>Class chat</h2></div><span class="online-label"><i></i> Class online</span></div><div class="chat-messages"><div class="system-message">Messages and moderation are shared with the original E3 class chat.</div></div>`; const messages = transcript.querySelector(".chat-messages"); chatMessages.forEach((message) => { const line = el("div", `dashboard-chat-line ${message.kind || "chat"}`); line.textContent = message.text; messages.appendChild(line); }); const form = el("form", "dashboard-chat-form"); form.innerHTML = `<input aria-label="Chat message" maxlength="240" placeholder="Type chat or /helpadmin"><button type="submit">Send</button>`; const input = form.querySelector("input"); ["keydown", "keyup", "keypress"].forEach((eventName) => input.addEventListener(eventName, (event) => event.stopPropagation())); form.addEventListener("submit", (event) => { event.preventDefault(); const text = input.value.trim(); if (text && onSendChat(text)) input.value = ""; }); transcript.appendChild(form); wrap.appendChild(transcript); requestAnimationFrame(() => { messages.scrollTop = messages.scrollHeight; }); return wrap; }
  function render(view = activeView) { avatarPreview?.dispose?.(); avatarPreview = null; activeView = view; Object.entries(navButtons).forEach(([key, button]) => button.classList.toggle("active", key === view || (view === "study" && key === "simulations"))); const labels = { overview: "Mission Overview", academics: "Academic Record", students: "Class Roster", people: "People & Access", achievements: "Achievements", inventory: "Quests & Inventory", avatar: "Avatar", simulations: "Learning Labs", study: "Orbital Study Archive", chat: "Class Chat" }; titleGroup.querySelector("h1").textContent = labels[view] || "Student Workspace"; viewport.replaceChildren(view === "academics" ? renderAcademics() : view === "students" && isAdmin ? renderStudents() : view === "people" && isAdmin ? renderPeople() : view === "achievements" ? renderAchievements() : view === "inventory" ? renderInventoryAndQuests() : view === "avatar" ? renderAvatar() : view === "simulations" ? renderSimulations() : view === "study" ? renderStudySession() : view === "chat" ? renderChat() : renderOverview()); const student = getStudent(); const rank = getProgression()?.profileRank || {}; classPill.textContent = student.className || "Class connected"; userChip.querySelector("strong").textContent = student.name || "Student"; userChip.querySelector(".rank-line").textContent = `Level ${rank.level || 1} · ${rank.label || "Recruit"}`; userChip.querySelector(".chapter-line").textContent = `Current chapter: ${student.currentChapter || "Not assigned"}`; userChip.querySelector(".user-initial").textContent = (student.name || "S").charAt(0).toUpperCase(); }
  nav.addEventListener("click", (event) => { const button = event.target.closest("button[data-view]"); if (button) render(button.dataset.view); }); render();
  return { show() { shell.hidden = false; render(activeView); }, hide() { shell.hidden = true; avatarPreview?.dispose?.(); avatarPreview = null; }, refresh() { if (!shell.hidden) render(activeView); }, setMissionPosition(index) { currentMissionPosition = Math.max(0, Math.min(MISSION_STOPS.length - 1, Number(index) || 0)); if (activeView === "achievements" && !shell.hidden) render("achievements"); }, appendChat(message) { chatMessages.push(message); chatMessages = chatMessages.slice(-100); if (activeView === "chat" && !shell.hidden) render("chat"); }, enqueueAchievement(achievement) { achievementQueue.push(achievement); if (!activeAchievement) showNextAchievement(); }, destroy() { avatarPreview?.dispose?.(); window.removeEventListener("keydown", advanceAchievement); shell.remove(); } };
}
