-- Render-independent E3 class chat. Safe to run repeatedly.
create table if not exists public.class_messages (
  message_id bigint generated by default as identity primary key,
  class_id uuid not null references public.classes(class_id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  body text not null check (char_length(body) between 1 and 240),
  created_at timestamptz not null default now()
);

create index if not exists class_messages_class_created_idx
  on public.class_messages (class_id, created_at desc);

alter table public.class_messages enable row level security;

create or replace function public.e3_can_access_class(requested_class_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select
    coalesce(auth.jwt() -> 'app_metadata' ->> 'e3_role', '') = 'teacher'
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'mnelsen@susd.net'
    or exists (
      select 1 from public.class_memberships membership
      where membership.user_id = auth.uid()
        and membership.class_id = requested_class_id
    );
$$;

revoke all on function public.e3_can_access_class(uuid) from public, anon;
grant execute on function public.e3_can_access_class(uuid) to authenticated, service_role;

drop policy if exists "class members can read messages" on public.class_messages;
create policy "class members can read messages" on public.class_messages
  for select to authenticated using (public.e3_can_access_class(class_id));

drop policy if exists "class members can send messages" on public.class_messages;
create policy "class members can send messages" on public.class_messages
  for insert to authenticated
  with check (user_id = auth.uid() and public.e3_can_access_class(class_id));

revoke all on table public.class_messages from anon, authenticated;
grant select, insert on table public.class_messages to authenticated;
grant select, insert, update, delete on table public.class_messages to service_role;
grant usage, select on sequence public.class_messages_message_id_seq to authenticated, service_role;

do $publication$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'class_messages'
  ) then
    alter publication supabase_realtime add table public.class_messages;
  end if;
end
$publication$;
